alias grep='grep --color=auto'
alias hg='history | grep'
alias ls='ls -F'
alias ll='ls -l'
alias lll='ls -lahtr'
alias lt='du -sh * | sort -h'
alias fna='sudo find / -name'
alias fni='sudo find / -iname'
